server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service:8080
          predicates:
            - Path=/products/**
        - id: customer-service
          uri: http://customer-service:8080
          predicates:
            - Path=/customers/**
        - id: order-service
          uri: http://order-service:8080
          predicates:
            - Path=/orders/**
